image: Visual Studio 2019
configuration:
  - Release
platform:
  - x64
  - x86
clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive
cache:
  - C:\tools\vcpkg\installed\ -> nas2d-core\InstallVcpkgDeps.bat
install:
  - vcpkg integrate install
  - call nas2d-core\InstallVcpkgDeps.bat
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true
build:
  project: proj/vs2019/NAS2D Test Suite.sln
